### ISSUE TITLE
uid 관련 문제 입니다.

### ISSUE THREAD

**Issue by minsuk257** [TooShy/HufsTalk_Server#2]
저희가 페북에서 받아오는 uid값이 int형보다 훨신큰 15자리 정수라 자료형이 맞지 않아 서버 오류가 떴습니다. 그리고 가입 조건에 이메일을 빼야 할것 같습니다. 페이스북에 이메일 정보를 입력하지 않은 사람들(승형이형) 이 있어서 이메일은 빼야할것 같습니다 ㅠㅠ

**Comment by tokirin** [comment]
Solved
